language: c
compiler:
  - gcc
  - clang
branches:
  only:
    - master
    - coveralls

before_install:
  - sudo pip install cpp-coveralls

script: make && cd test && make test

after_success:
  - coveralls --verbose --gcov-options '\-lp' -r .. -E '.*test*'
